general:
  os: "windows"  #"linux"
  seed: 10 #11 #50 #51 #100 #101 #150 #42 #7 # 1
  place_name: "Dresden, Germany"
  proj_lib_path: "../Lib/site-packages/rasterio/proj_data"


paths:
  raw_ground_truth_path: "../data/raw/ground truth"
  dresden_boundary_path: "../data/raw/boundary/dresden_boundary.geojson"
  eua_dataset_path: "../data/raw/ground truth/DE009L2_DRESDEN_UA2018_v013.gpkg"
  
  # Ground truth datasets
  green_openspaces_path: "../data/raw/ground truth/green_and_openspaces_dataset.geojson"
  parks_greenspaces_path: "../data/raw/ground truth/parks_and_greenspaces_dataset.geojson"
  leisure_area_path: "../data/raw/ground truth/leisure_area_dataset.geojson"
  point_parks_path: "../data/raw/ground truth/point_parks_and_gardens_dataset.geojson"
  park_zwirnmuhle_path: "../data/raw/ground truth/park_an_der_zwirnmuhle_polygon.geojson"
  
  # Processed ground truth paths
  processed_ground_truth_path: "../data/processed/ground truth"
  gt_vector_path: "../data/processed/ground truth/dresden_pugs_gt.geojson"
  gt_undissolved_path: "../data/processed/ground truth/dresden_pugs_gt_undissolved.geojson"
  gt_raster_path: "../data/processed/ground truth/dresden_pugs_gt.geotiff"
  clipped_gt_raster_path: "../data/processed/ground truth/clipped_dresden_pugs_gt.geotiff"
  eua_pugs_path: "../data/processed/ground truth/eua_pugs_dataset.geojson"
  parks_i_type_path: "../data/processed/ground truth/i_parks_type_dataset.geojson"
  
  # Raw OSM data paths
  raw_osm_path: "../data/raw/osm"
  green_landuse_path: "../data/raw/osm/green space/green_landuse_area_dresden.geojson"
  green_leisure_path: "../data/raw/osm/green space/green_leisure_area_dresden.geojson"
  green_natural_path: "../data/raw/osm/green space/green_natural_area_dresden.geojson"
  green_campsite_path: "../data/raw/osm/green space/green_campsite_area_dresden.geojson"
  poi_amenity_path: "../data/raw/osm/amenity/poi_amenity_dresden.geojson"
  poi_leisure_path: "../data/raw/osm/amenity/poi_leisure_dresden.geojson"
  poi_viewpoint_path: "../data/raw/osm/amenity/poi_viewpoint_dresden.geojson"
  footpath_network_path: "../data/raw/osm/network/footpath_network_edges.geojson"
  
  # Processed OSM data paths  # by deffault filtered version is used
  processed_osm_path: "../data/processed/osm"
  pugs_vector_path: "../data/processed/osm/public_green_spaces_dresden.geojson"
  pugs_vector_nofiltered_path: "../data/processed/osm/public_green_spaces_dresden_nofiltered.geojson"    #original version
  pugs_mask_path: "../data/processed/osm/public_green_spaces_dresden.geotiff"
  pugs_nofiltered_mask_path: "../data/processed/osm/public_green_spaces_dresden_nofiltered.geotiff"
  pugs_sdt_path: "../data/processed/osm/sdt_public_green_spaces_dresden.geotiff"
  pugs_nofiltered_sdt_path: "../data/processed/osm/sdt_public_green_spaces_dresden_nofiltered.geotiff"

  # Raw Sentinel-2 data paths
  raw_sentinel_path: "../data/raw/sentinel-2/cm_sentinel2_l1c_openeo_med_4months_dresden.geotiff"

  # Processed Sentinel-2 data paths
  processed_sentinel_path: "../data/processed/sentinel-2"
  clipped_image_path: "../data/processed/sentinel-2/stacked_sentinel2_dresden_clipped.geotiff"
  whole_image_path: "../data/processed/sentinel-2/stacked_sentinel2_dresden.geotiff"
  
  # Tile paths
  tiles_folder_path: "../data/processed/tiles"
  train_image_path: "../data/processed/tiles/train"
  val_image_path: "../data/processed/tiles/val"
  test_image_path: "../data/processed/tiles/test"
  
  # Model paths
  logger_path: "../s{seed}/models"
  checkpoint_folder: "trained_models"
  test_result_folder: "test_result"
  
  # Results paths
  gt_vs_pred_template: "../s{seed}/reports/figures/gt_vs_pred/v{version}"
  loss_graph_template: "../s{seed}/reports/figures/loss graph/loss_graph_v{version}.png" 
  fn_area_template: "../s{seed}/results/fn_maps/fn_area_v{version}.geotiff"
  fp_area_template: "../s{seed}/results/fp_maps/fp_area_v{version}.geotiff"
  clipped_prediction_template: "../s{seed}/results/clipped_prediction/clipped_pred_v{version}.geotiff"
  whole_prediction_template: "../s{seed}/results/whole_area_prediction/pred_v{version}.geotiff"
  test_metrics_template: "../s{seed}/models/test_result/version_{version}/test_metrics.csv"
  train_metrics_template: "../s{seed}/models/trained_models/version_{version}/metrics.csv"
  per_instance_recall_template: "../s{seed}/models/test_result/version_{version}/per_instance_recall.csv"
  per_instance_recall_path_global: "../s{seed}/results/per_instance_recall_analysis.csv"

  # Report paths
  sentinel_pred_raster_path: "../s{seed}/results/clipped_prediction/clipped_pred_v0.geotiff"
  with_osm_pred_raster_path: "../s{seed}/results/clipped_prediction/clipped_pred_v1.geotiff"
  pred_raster_path: "../s{seed}/results/clipped_prediction/clipped_pred_v{version}.geotiff"
  analysis_graph_path: "../s{seed}/reports/figures/others/overlap_pct_with_gs_size.png"
  dissolved_by_area_group_gt_path: "../data/processed/ground truth/pugs_by_area_group.geojson"
  osm_classification_path: "../s{seed}/reports/figures/others/osm_pugs_classification_method.png"
data:
  # Sentinel-2 data configuration
  spatial_extent: {"west": 13.5793237, "south": 50.974937, "east": 13.9660626, "north": 51.1777202}
  temporal_extent: ["2024-05-01", "2024-08-31"]
  max_cloud_cover: 5

  # Data splitting - tiles ids
  train_index_list: [2, 3, 9, 11, 12, 13, 15, 16, 18, 20, 23]
  val_index_list: [7, 17, 19]
  test_index_list: [8, 14, 22]
  
  # crs
  crs: 32633

model:
  # Model architecture
  architecture: "unet"
  backbone: "resnet50"
  weight: "SENTINEL2_ALL_MOCO"

  # Training parameters
  batch_size: 16
  # loss_func: "jaccard"  # Options: "bce", "focal", "jaccard"
  learning_rate: 0.0001
  epochs: 50
  patience: 10  # For early stopping
  
  # Hardware settings
  training_num_workers: 8
  validation_num_workers: 4
  persistent_workers: "True"   # avoids worker respawn cost every epoch
  pin_memory: "True"
  test_num_workers: 2
  accelerator: "gpu" # Options: "cpu", "gpu"
  
  # Model experiment version - here change for # bands/loss
  version: 1

models:
  0: 
    # selected bands/input / 
    band_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]  # only sentinel-2 bands
    # Training parameters
    loss_func: "jaccard"  # Options: "bce", "focal", "jaccard"
    # Model experiment version
    version: 0
  
  1: 
    # selected bands/input / 
    band_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]  # sentinel-2 bands + OSM data binary mask
    # Training parameters - with OSM data binary mask
    loss_func: "jaccard"  # Options: "bce", "focal", "jaccard"
    # Model experiment version
    version: 1
  
  2: 
    # selected bands/input / 
    band_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14]  # sentinel-2 bands + OSM data SDT
    # Training parameters - with OSM data SDT
    loss_func: "jaccard"  # Options: "bce", "focal", "jaccard"
    # Model experiment version
    version: 2

  3: 
    # selected bands/input / 
    band_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]  # only sentinel-2 bands
    # Training parameters - 
    loss_func: "bce"  # Options: "bce", "focal", "jaccard"
    # Model experiment version
    version: 3
  
  4: 
    # selected bands/input / 
    band_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]  # sentinel-2 bands + OSM data binary mask
    # Training parameters - with OSM data binary mask
    loss_func: "bce"  # Options: "bce", "focal", "jaccard"
    # Model experiment version
    version: 4
  
  5: 
    # selected bands/input / 
    band_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14]  # sentinel-2 bands + OSM data SDT
    # Training parameters - with OSM data SDT
    loss_func: "bce"  # Options: "bce", "focal", "jaccard"
    # Model experiment version
    version: 5

  6: 
    # selected bands/input / 
    band_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]  # only sentinel-2 bands
    # Training parameters 
    loss_func: "focal"  # Options: "bce", "focal", "jaccard"
    # Model experiment version
    version: 6
  
  7: 
    # selected bands/input / 
    band_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]  # sentinel-2 bands + OSM data binary mask
    # Training parameters - with OSM data binary mask
    loss_func: "focal"  # Options: "bce", "focal", "jaccard"
    # Model experiment version
    version: 7
  
  8: 
    # selected bands/input / 
    band_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14]  # sentinel-2 bands + OSM data SDT
    # Training parameters - with OSM data SDT
    loss_func: "focal"  # Options: "bce", "focal", "jaccard"
    # Model experiment version
    version: 8


